# Generated by Django 2.2.12 on 2022-05-14 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('ide', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(blank=True, max_length=250, null=True)),
                ('patient_id', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, default='th.jpeg', null=True, upload_to='predictions/')),
                ('feature', models.CharField(blank=True, max_length=250, null=True)),
                ('f_value', models.CharField(blank=True, max_length=250, null=True)),
                ('predicted', models.BooleanField(default=False)),
                ('date_scanned', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
